CREATE TABLE IF NOT EXISTS gruppi (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS inviti (
  id INT AUTO_INCREMENT PRIMARY KEY,
  token VARCHAR(32) NOT NULL UNIQUE,
  nome_gruppo VARCHAR(255) NOT NULL,
  gruppo_id INT DEFAULT NULL,
  note TEXT,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_token (token),
  FOREIGN KEY (gruppo_id) REFERENCES gruppi(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS invitati (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invito_id INT NOT NULL,
  nome VARCHAR(255) NOT NULL,
  genere CHAR(1) DEFAULT 'M',
  confermato TINYINT DEFAULT NULL,
  confirmed_at TIMESTAMP NULL DEFAULT NULL,
  FOREIGN KEY (invito_id) REFERENCES inviti(id) ON DELETE CASCADE,
  INDEX idx_invito (invito_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS foto (
  id INT AUTO_INCREMENT PRIMARY KEY,
  filename VARCHAR(255) NOT NULL,
  nome_autore VARCHAR(255) DEFAULT NULL,
  commento TEXT,
  uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_uploaded (uploaded_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
